import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    width: '100%',
    backgroundColor: '#012FA7',
    paddingHorizontal: '8%',
    paddingTop: 5,
  },
  backButton: {
    marginRight: 10,
  },
  backButtonText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  searchAdd: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    maxHeight: 150,
  },
  searchInput: {
    color: '#012FA7',
    width: '70%',
    alignSelf: 'center',
    height: 50,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
  },
  addGroupButton: {
    height: 50,
    width: 50,
    backgroundColor: '#012FA7',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gearIcon: {
    width: 24,
    height: 24,
  },
  backgroundImage: {
    position: 'absolute',
    top: '45%',
    left: '25%',
    width: 500,
    height: 500,
    zIndex: 0,
    opacity: 0.65,
  },
  loadingText: {
    fontSize: 18,
    color: '#000000',
  },
  errorText: {
    fontSize: 18,
    color: 'red',
  },
  content: {
    alignSelf: 'center',
    width: '85%',
    flex: 1,
  },
  columnWrapper: {
    justifyContent: 'space-between',
    gap: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    width: '80%',
    height: '60%',
    backgroundColor: '#FFFFFF',
    borderColor: '#012FA7',
    borderWidth: 2,
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
  },
  modalTitle: {
    color: '#012FA7',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  tabContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#012FA7',
  },
  tabText: {
    color: '#666',
    fontSize: 14,
    fontWeight: '500',
  },
  activeTabText: {
    color: '#012FA7',
    fontWeight: 'bold',
  },
  tabContent: {
    width: '100%',
    flex: 1,
  },
  modalSearchInput: {
    color: '#012FA7',
    width: '100%',
    height: 40,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
    marginBottom: 15,
  },
  groupsList: {
    maxHeight: 200,
    width: '100%',
  },
  groupItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  groupItemSelected: {
    backgroundColor: '#E3ECFF',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#012FA7',
    borderRadius: 4,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    width: 12,
    height: 12,
    backgroundColor: '#012FA7',
    borderRadius: 2,
  },
  groupItemText: {
    fontSize: 16,
    color: '#012FA7',
  },
  noGroupsText: {
    textAlign: 'center',
    color: '#666',
    fontStyle: 'italic',
    padding: 20,
  },
  modalButtons: {
    width: '100%',
  },
  modalButton: {
    padding: 12,
    borderRadius: 5,
    marginBottom: 10,
    alignItems: 'center',
  },
  addButton: {
    backgroundColor: '#28a745',
  },
  removeButton: {
    backgroundColor: '#FF4500',
  },
  cancelButton: {
    backgroundColor: '#6c757d',
  },
  buttonDisabled: {
    backgroundColor: '#CCCCCC',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  courseFilterContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  courseButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#E3ECFF',
    borderRadius: 20,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#012FA7',
  },
  courseButtonActive: {
    backgroundColor: '#012FA7',
  },
  courseButtonText: {
    color: '#012FA7',
    fontSize: 14,
    fontWeight: '500',
  },
  courseButtonTextActive: {
    color: '#FFFFFF',
  },
  groupCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#012FA7',
    borderWidth: 2,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  groupCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  groupCardTitle: {
    color: '#012FA7',
    fontSize: 18,
    fontWeight: 'bold',
  },
  courseBadge: {
    backgroundColor: '#012FA7',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  courseBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  groupCardDetails: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: 12,
  },
  groupCardInfo: {
    color: '#333',
    fontSize: 14,
    marginBottom: 4,
  },
  mainTabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#E3ECFF',
    marginHorizontal: 20,
    borderRadius: 10,
    padding: 4,
  },
  mainTab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
  },
  mainTabActive: {
    backgroundColor: '#012FA7',
  },
  mainTabText: {
    color: '#012FA7',
    fontSize: 14,
    fontWeight: '600',
  },
  mainTabTextActive: {
    color: '#FFFFFF',
  },
  mainInfoCard: {
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
    marginBottom: 4,
  },
  themeSection: {
    marginVertical: 12,
  },
  themeBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  themeText: {
    fontSize: 16,
    color: '#333',
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  infoItem: {
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    color: '#012FA7',
    fontWeight: '500',
  },
  gradeSection: {
    alignItems: 'center',
    marginBottom: 16,
  },
  gradeBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  gradeBadgeHigh: {
    backgroundColor: '#4CAF50',
  },
  gradeBadgeMedium: {
    backgroundColor: '#FFC107',
  },
  gradeBadgeLow: {
    backgroundColor: '#F44336',
  },
  gradeBadgeText: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: 'bold',
  },
  additionalInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  infoGridItem: {
    width: '50%',
    paddingVertical: 8,
  },
  infoGridLabel: {
    fontSize: 12,
    color: '#666',
  },
  infoGridValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#012FA7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: 'bold',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: '#666',
    width: 120,
  },
});