import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  backgroundImage: {
    position: 'absolute',
    top: '45%',
    left: '25%',
    width: 500,
    height: 500,
    zIndex: 0,
    opacity: 0.65,
    overflow: 'hidden',
  },
  header: {
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    width: '100%',
    backgroundColor: '#012FA7',
    paddingHorizontal: '8%',
    paddingTop: 5,
  },
  backButton: {
    marginRight: 10,
  },
  backButtonText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  searchInput: {
    color: '#012FA7',
    width: '85%',
    alignSelf: 'center',
    height: 50,
    marginTop: 50,
    marginBottom: 20,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
  },
  loadingText: {
    fontSize: 18,
    color: '#000000',
  },
  errorText: {
    fontSize: 18,
    color: 'red',
  },

  // Таблица в стиле StudentsScreen
  tableContainer: {
    flex: 1,
    width: '95%',
    alignSelf: 'center',
    marginBottom: 20,
  },
  fixedColumn: {
    width: 30,
    backgroundColor: '#F8F9FC',
  },
  fixedColumnHeader: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#012FA7',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  fixedRow: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderRadius: 8,
    borderColor: '#012FA7',
    backgroundColor: '#0130a72f',
  },
  fixedRowText: {
    fontWeight: 'bold',
    color: '#000000',
  },
  tableRow: {
    flexDirection: 'row',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    minHeight: 60,
    borderBottomWidth: 1,
    borderBottomColor: '#012FA7',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  headerRow: {
    backgroundColor: '#012FA7',
  },
  studentColumnHeader: {
    width: 180,
    paddingLeft: 10,
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  toolsColumnHeader: {
    flex: 1,
    minWidth: 150,
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 10,
  },

  marksHeaderTitleContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 4,
  },
  marksHeaderTitleText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  markHeaderContainer: {
    minWidth: 55,
    marginHorizontal: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markHeaderButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  ratingColumnHeader: {
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  columnHeaderText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  studentColumn: {
    width: 180,
    justifyContent: 'center',
    paddingLeft: 10,
    backgroundColor: '#F8F9FC',
    borderRightWidth: 1,
    borderRightColor: '#012FA7',
  },
  studentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
  },
  marksRow: {
    flexDirection: 'row',
    minWidth: 200,
    backgroundColor: '#FFFFFF',
  },
  markCell: {
    padding: 8,
    marginHorizontal: 2,
    borderRadius: 4,
    width: 55,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  ratingColumn: {
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FC',
    borderLeftWidth: 1,
    borderLeftColor: '#012FA7',
  },
  ratingText: {
    fontSize: 16,
    fontWeight: 'bold',
    padding: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: 'center',
  },
  highRating: {
    backgroundColor: '#4CAF50',
    color: '#FFFFFF',
  },
  mediumRating: {
    backgroundColor: '#FFC107',
    color: '#000000',
  },
  lowRating: {
    backgroundColor: '#F44336',
    color: '#FFFFFF',
  },
  noRating: {
    backgroundColor: 'lightgray',
    color: 'white',
  },
});
