import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  backgroundImage: {
    position: 'absolute',
    top: '45%',
    left: '25%',
    width: 500,
    height: 500,
    zIndex: 0,
    opacity: 0.65,
    overflow: 'hidden',
  },
  header: {
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    width: '100%',
    backgroundColor: '#012FA7',
    paddingHorizontal: '8%',
    paddingTop: 5,
  },
  backButton: {
    marginRight: 10,
  },
  backButtonText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  searchInput: {
    color: '#012FA7',
    width: '85%',
    alignSelf: 'center',
    height: 50,
    marginTop: 50,
    marginBottom: 20,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
  },
  loadingText: {
    fontSize: 18,
    color: '#000000',
    textAlign: 'center',
    marginTop: 20,
  },
  errorText: {
    fontSize: 18,
    color: 'red',
    textAlign: 'center',
    marginTop: 20,
  },
  tableContainer: {
    width: '85%',
    alignSelf: 'center',
    flexGrow: 1,
    marginVertical: 20,
  },
  dayContainer: {
    marginBottom: 15,
  },
  dayHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 10,
    textAlign: 'center',
  },
  scheduleItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#012FA7',
    borderRadius: 8,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, .8)',
    marginBottom: 8,
  },
  noClassesItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderRadius: 8,
    padding: 20,
    backgroundColor: 'rgba(255, 255, 255, .6)',
  },
  noClassesText: {
    color: '#666666',
    fontSize: 16,
    fontStyle: 'italic',
  },
  scheduleInfo: {
    flex: 3,
  },
  scheduleText: {
    color: '#012FA7',
    fontSize: 14,
    marginBottom: 2,
  },
  subgroupText: {
    color: '#012FA7',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 4,
  },
  subjectContainer: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  subjectText: {
    color: '#012FA7',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'right',
  },
  ratingText: {
    fontSize: 16,
    fontWeight: 'bold',
    padding: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: 'center',
  },
  highRating: {
    backgroundColor: '#4CAF50',
    color: '#FFFFFF',
  },
  mediumRating: {
    backgroundColor: '#FFC107',
    color: '#000000',
  },
  lowRating: {
    backgroundColor: '#F44336',
    color: '#FFFFFF',
  },
  noRating: {
    backgroundColor: 'lightgray',
    color: 'white',
  },
});
