import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  header: {
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    width: '100%',
    backgroundColor: '#012FA7',
    paddingHorizontal: '8%',
    paddingTop: 5,
  },
  backButton: { marginRight: 10 },
  backButtonText: { marginTop: 20, color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
  headerText: { marginTop: 20, color: '#FFFFFF', fontSize: 20, fontWeight: 'bold' },
  mainTabsContainer: {
    flexDirection: 'row',
    marginTop: 60,
    marginHorizontal: 20,
    backgroundColor: '#F0F4FF',
    borderRadius: 10,
    padding: 4,
  },
  mainTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  mainTabActive: {
    backgroundColor: '#012FA7',
  },
  mainTabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#012FA7',
  },
  mainTabTextActive: {
    color: '#FFFFFF',
  },
  
  searchInput: {
    color: '#012FA7',
    width: '85%',
    alignSelf: 'center',
    height: 50,
    marginTop: 20,
    marginBottom: 20,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
  },
  tableContainer: { flex: 1, width: '95%', alignSelf: 'center' },
  fixedColumn: { width: 30, backgroundColor: '#F8F9FC' },
  fixedColumnHeader: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#012FA7',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  columnHeaderText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14 },
  fixedRow: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderRadius: 8,
    borderColor: '#012FA7',
    backgroundColor: '#0130a72f',
  },
  fixedRowText: { fontWeight: 'bold', color: '#000000' },
  tableRow: {
    flexDirection: 'row',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    minHeight: 60,
    borderBottomWidth: 1,
    borderBottomColor: '#012FA7',
    alignItems: 'center',
  },
  headerRow: { backgroundColor: '#012FA7' },
  studentColumnHeader: {
    width: 180,
    paddingLeft: 10,
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  toolsColumnHeader: {
    flex: 1,
    flexDirection: 'row',
    minWidth: 150,
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  markHeaderContainer: {
    minWidth: 55,
    marginHorizontal: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markHeaderButtonText: { color: '#FFFFFF', fontSize: 24, fontWeight: 'bold' },
  ratingColumnHeader: { width: 80, justifyContent: 'center', alignItems: 'center' },
  studentColumn: {
    width: 180,
    justifyContent: 'center',
    paddingLeft: 10,
    backgroundColor: '#F8F9FC',
    borderRightWidth: 1,
    borderRightColor: '#012FA7',
  },
  studentName: { fontWeight: 'bold', fontSize: 16, color: '#000000' },
  marksRow: { flexDirection: 'row', minWidth: 200, backgroundColor: '#FFFFFF' },
  markCell: {
    padding: 8,
    marginHorizontal: 2,
    borderRadius: 4,
    width: 55,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 14 },
  ratingColumn: {
    width: 80,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FC',
    borderLeftWidth: 1,
    borderLeftColor: '#012FA7',
  },
  ratingText: {
    fontWeight: 'bold',
    padding: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: 'center',
    fontSize: 16,
  },
  highRating: { backgroundColor: '#4CAF50', color: '#FFFFFF' },
  mediumRating: { backgroundColor: '#FFC107', color: '#000000' },
  lowRating: { backgroundColor: '#F44336', color: '#FFFFFF' },
  attendanceHeaderContainer: {
    minWidth: 55,
    marginHorizontal: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attendanceHeaderText: {
    color: '#FFFFFF',
    fontSize: 10,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  attendancesRow: {
    flexDirection: 'row',
    minWidth: 200,
    backgroundColor: '#FFFFFF',
  },
  attendanceCell: {
    padding: 8,
    marginHorizontal: 2,
    borderRadius: 4,
    width: 55,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attendanceText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  attendanceStudentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 20,
    textAlign: 'center',
  },
  attendanceForm: {
    width: '100%',
  },
  attendanceLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 10,
  },
  attendanceStatusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statusButton: {
    flex: 1,
    marginHorizontal: 5,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  statusButtonSelected: {
    borderColor: '#012FA7',
    borderWidth: 2,
  },
  statusButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  attendanceCommentInput: {
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#000',
    backgroundColor: '#F0F4FF',
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 20,
  },
  attendanceButtons: {
    width: '100%',
  },
  loadingText: { fontSize: 18, color: '#000000', textAlign: 'center', marginTop: 50 },
  errorText: { fontSize: 18, color: 'red', textAlign: 'center', marginTop: 50, marginBottom: 20 },
  retryButton: { backgroundColor: '#012FA7', padding: 12, borderRadius: 5, alignSelf: 'center' },
  retryButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainer: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  modalContentScroll: {
    width: '100%',
  },
  closeButtonTop: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 24,
    height: 24,
    borderRadius: 16,
    backgroundColor: '#dc3545',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  closeButtonTopText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  tabContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#E0E0E0',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#012FA7',
  },
  tabText: {
    color: '#666',
    fontSize: 15,
    fontWeight: '500',
  },
  activeTabText: {
    color: '#012FA7',
    fontWeight: 'bold',
  },
  editTabContent: {
    width: '100%',
    alignItems: 'center',
  },
  editInfoBlock: {
    width: '100%',
    backgroundColor: '#F8F9FC',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
  },
  modalTitle: {
    color: '#012FA7',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  markNumberText: {
    color: '#012FA7',
    fontSize: 14,
    marginBottom: 5,
    textAlign: 'center',
  },
  currentValueText: {
    color: '#666',
    fontSize: 12,
    marginBottom: 5,
    textAlign: 'center',
  },
  modalInput: {
    color: '#012FA7',
    borderWidth: 1,
    borderColor: '#012FA7',
    padding: 10,
    borderRadius: 5,
    width: '100%',
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 16,
  },
  modalButtons: {
    width: '100%',
  },
  modalButton: {
    padding: 12,
    borderRadius: 5,
    marginBottom: 10,
    alignItems: 'center',
  },
  saveButton: {
    backgroundColor: '#28a745',
  },
  deleteButton: {
    backgroundColor: '#dc3545',
  },
  cancelButton: {
    backgroundColor: '#6c757d',
  },
  buttonDisabled: {
    backgroundColor: '#CCCCCC',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  tabContentScroll: {
    width: '100%',
    maxHeight: 450,
  },
  mainInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  gradeSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  gradeBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 60,
    alignItems: 'center',
  },
  gradeBadgeHigh: {
    backgroundColor: '#4CAF50',
  },
  gradeBadgeMedium: {
    backgroundColor: '#FFC107',
  },
  gradeBadgeLow: {
    backgroundColor: '#F44336',
  },
  gradeBadgeText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  themeSection: {
    marginBottom: 15,
  },
  themeBox: {
    backgroundColor: '#F0F4FF',
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#012FA7',
  },
  themeText: {
    fontSize: 15,
    color: '#000',
    lineHeight: 22,
  },
  infoRow: {
    marginBottom: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  infoItem: {
    width: '100%',
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 5,
  },
  infoValue: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  filesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 12,
  },
  filesContainer: {
    gap: 8,
  },
  fileChip: {
    backgroundColor: '#E3F2FD',
    padding: 10,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#2196F3',
  },
  fileChipText: {
    color: '#1976D2',
    fontSize: 14,
  },
  additionalInfoCard: {
    backgroundColor: '#F8F9FC',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  additionalInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoGridItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  infoGridLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  infoGridValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#012FA7',
  },
  replacementBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  replacementYes: {
    backgroundColor: '#E8F5E9',
  },
  replacementNo: {
    backgroundColor: '#FFEBEE',
  },
  replacementText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  chatInputContainer: {
    width: '100%',
    marginBottom: 15,
    backgroundColor: '#F8F9FC',
    padding: 12,
    borderRadius: 12,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputWrapper: {
    flex: 1,
    position: 'relative',
  },
  newCommentInput: {
    minHeight: 40,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingRight: 40,
    paddingVertical: 8,
    color: '#012FA7',
    fontSize: 14,
    backgroundColor: '#FFFFFF',
  },
  attachIcon: {
    position: 'absolute',
    right: 10,
    top: 10,
  },
  attachIconText: {
    fontSize: 20,
  },
  sendButton: {
    marginLeft: 8,
    backgroundColor: '#012FA7',
    borderRadius: 8,
    padding: 10,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    width: 20,
    height: 20,
    tintColor: '#FFFFFF',
  },
  selectedFilesContainer: {
    marginTop: 10,
  },
  selectedFilesLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 5,
  },
  fileItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderRadius: 6,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  fileName: {
    color: '#012FA7',
    fontSize: 13,
    flex: 1,
  },
  removeFileText: {
    color: '#FF0000',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  chatMessagesContainer: {
    width: '100%',
    marginBottom: 15,
  },
  messageCard: {
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  messageTeacher: {
    backgroundColor: '#E3F2FD',
    marginRight: 20,
  },
  messageStudent: {
    backgroundColor: '#E8F5E9',
    marginLeft: 20,
  },
  messageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  messageSender: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  teacherSender: {
    color: '#1976D2',
  },
  studentSender: {
    color: '#388E3C',
  },
  messageDate: {
    fontSize: 11,
    color: '#666',
  },
  messageText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
  },
  messageFiles: {
    marginTop: 8,
    gap: 6,
  },
  messageFileChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    padding: 8,
    borderRadius: 6,
  },
  messageFileText: {
    color: '#1976D2',
    fontSize: 12,
  },
  emptyChat: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyChatIcon: {
    fontSize: 48,
    marginBottom: 10,
    opacity: 0.3,
  },
  emptyChatText: {
    fontSize: 16,
    color: '#666',
  },
  propertiesCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  propertySection: {
    marginBottom: 20,
  },
  propertyLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 8,
  },
  propertyInput: {
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#000',
    backgroundColor: '#F0F4FF',
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  updateButton: {
    backgroundColor: '#28a745',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  updateButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  infoSection: {
    backgroundColor: '#F8F9FC',
    borderRadius: 8,
    padding: 15,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginBottom: 15,
  },
  infoSectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 15,
  },
  infoItemVertical: {
    marginBottom: 15,
    alignItems: 'flex-start',
  },
  infoItemHeader: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  infoItemValueLarge: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
    lineHeight: 22,
  },
  dropdownButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0F4FF',
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  dropdownButtonText: {
    color: '#012FA7',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  dropdownArrow: {
    color: '#012FA7',
    fontSize: 12,
    marginLeft: 8,
  },
  dropdownList: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    maxHeight: 200,
    marginBottom: 10,
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  dropdownItemSelected: {
    backgroundColor: '#E3F2FD',
  },
  dropdownItemText: {
    color: '#333',
    fontSize: 14,
  },
  dropdownItemTextSelected: {
    color: '#012FA7',
    fontWeight: 'bold',
  },
  gradePickerContainer: {
    width: '100%',
    marginBottom: 15,
  },
  gradePickerButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F0F4FF',
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    padding: 12,
  },
  gradePickerButtonText: {
    color: '#012FA7',
    fontSize: 16,
    fontWeight: '500',
    flex: 1,
  },
  gradePickerList: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    maxHeight: 250,
    marginTop: 8,
  },
  gradePickerItem: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    alignItems: 'center',
  },
  gradePickerItemSelected: {
    backgroundColor: '#E3F2FD',
  },
  gradePickerItemText: {
    color: '#333',
    fontSize: 16,
  },
  gradePickerItemTextSelected: {
    color: '#012FA7',
    fontWeight: 'bold',
    fontSize: 18,
  },
  gradeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gradeButton: {
    width: '30%',
    padding: 10,
    marginVertical: 5,
    backgroundColor: '#E0E0E0',
    borderRadius: 5,
    alignItems: 'center',
  },
  selectedGrade: {
    backgroundColor: '#4CAF50',
  },
  gradeText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  gradeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  gradeButtonSelected: {
    backgroundColor: '#4a63f6',
    borderColor: '#2e46c7',
    shadowColor: '#2e46c7',
  },
  gradeTextSelected: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 18,
  },
  lessonsList: {
    maxHeight: 400,
    width: '100%',
    marginBottom: 15,
  },
  lessonItem: {
    backgroundColor: '#F8F9FC',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  lessonItemSelected: {
    borderColor: '#012FA7',
    backgroundColor: '#E3F2FD',
  },
  lessonDate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 5,
  },
  lessonDetails: {
    fontSize: 14,
    color: '#333',
    marginBottom: 3,
  },
  lessonPair: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  lessonsModalButtons: {
    width: '100%',
  },
});