import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  backgroundImage: {
    position: 'absolute',
    top: '45%',
    left: '25%',
    width: 500,
    height: 500,
    zIndex: 0,
    opacity: 0.65,
    overflow: 'hidden',
  },
  header: {
    justifyContent: 'space-between',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    width: '100%',
    backgroundColor: '#012FA7',
    paddingHorizontal: '8%',
    paddingTop: 5,
  },
  backButton: {
    marginRight: 10,
  },
  backButtonText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerText: {
    marginTop: 20,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'right',
  },
  searchInput: {
    color: '#012FA7',
    width: '85%',
    alignSelf: 'center',
    height: 50,
    marginTop: 50,
    marginBottom: 20,
    backgroundColor: '#CCD5ED',
    paddingHorizontal: 16,
    borderRadius: 10,
    fontSize: 16,
  },
  loadingText: {
    fontSize: 18,
    color: '#000000',
    textAlign: 'center',
    marginTop: 20,
  },
  errorText: {
    fontSize: 18,
    color: 'red',
    textAlign: 'center',
    marginTop: 20,
  },
  horizontalScrollContainer: {
    flex: 1,
  },
  horizontalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  tableWrapper: {
    minWidth: 600,
  },
  tableHeader: {
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#012FA7',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    height: 50,
    minWidth: 600,
  },
  markColumnHeader: {
    width: 65,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  topicColumnHeader: {
    width: 175,
    justifyContent: 'center',
    paddingLeft: 8,
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  dateColumnHeader: {
    width: 100,
    justifyContent: 'center',
    paddingLeft: 8,
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  typeColumnHeader: {
    width: 150,
    justifyContent: 'center',
    paddingLeft: 8,
    borderRightWidth: 1,
    borderRightColor: '#FFFFFF',
  },
  teacherColumnHeader: {
    width: 120,
    justifyContent: 'center',
    paddingLeft: 8,
  },
  columnHeaderText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  tableContainer: {
    width: '100%',
    minWidth: 600,
  },
  tableRow: {
    flexDirection: 'row',
    minHeight: 50,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  noMarksRow: {
    flexDirection: 'row',
    minHeight: 50,
    backgroundColor: '#F8F9FC',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    minWidth: 600,
  },
  noMarksText: {
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
  },
  rowColumn: {
    padding: 0,
    borderRightWidth: 1,
    borderRightColor: '#E0E0E0',
  },
  markColumn: {
    width: 65,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FC',
  },
  topicColumn: {
    width: 175,
    justifyContent: 'center',
    paddingLeft: 8,
    paddingVertical: 8,
  },
  dateColumn: {
    width: 100,
    justifyContent: 'center',
    paddingLeft: 8,
    backgroundColor: '#F8F9FC',
    paddingVertical: 8,
  },
  typeColumn: {
    width: 150,
    justifyContent: 'center',
    paddingLeft: 8,
    paddingVertical: 8,
  },
  teacherColumn: {
    width: 120,
    justifyContent: 'center',
    paddingLeft: 8,
    backgroundColor: '#F8F9FC',
    paddingVertical: 8,
  },
  ratingText: {
    fontSize: 14,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 35,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  highRating: {
    backgroundColor: '#4CAF50',
    color: '#FFFFFF',
  },
  mediumRating: {
    backgroundColor: '#FFC107',
    color: '#000000',
  },
  lowRating: {
    backgroundColor: '#F44336',
    color: '#FFFFFF',
  },
  topicText: {
    fontSize: 12,
    color: '#000000',
  },
  dateText: {
    fontSize: 12,
    color: '#000000',
  },
  typeText: {
    fontSize: 12,
    color: '#000000',
  },
  teacherText: {
    fontSize: 12,
    color: '#000000',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainer: {
    width: '80%',
    maxHeight: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  closeButtonTop: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#dc3545',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  closeButtonTopText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },

  tabContainer: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#E0E0E0',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#012FA7',
  },
  tabText: {
    color: '#666',
    fontSize: 15,
    fontWeight: '500',
  },
  activeTabText: {
    color: '#012FA7',
    fontWeight: 'bold',
  },
  tabContentScroll: {
    width: '100%',
    maxHeight: 450,
  },
  mainInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  gradeSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  gradeBadge: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    minWidth: 60,
    alignItems: 'center',
  },
  gradeBadgeHigh: {
    backgroundColor: '#4CAF50',
  },
  gradeBadgeMedium: {
    backgroundColor: '#FFC107',
  },
  gradeBadgeLow: {
    backgroundColor: '#F44336',
  },
  gradeBadgeText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  themeSection: {
    marginBottom: 15,
  },
  themeBox: {
    backgroundColor: '#F0F4FF',
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#012FA7',
  },
  themeText: {
    fontSize: 15,
    color: '#000',
    lineHeight: 22,
  },
  infoRow: {
    marginBottom: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  infoItem: {
    width: '100%',
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 5,
  },
  infoValue: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },

  filesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 12,
  },
  filesContainer: {
    gap: 8,
  },
  fileChip: {
    backgroundColor: '#E3F2FD',
    padding: 10,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#2196F3',
  },
  fileChipText: {
    color: '#1976D2',
    fontSize: 14,
  },

  additionalInfoCard: {
    backgroundColor: '#F8F9FC',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  additionalInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoGridItem: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  infoGridLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  infoGridValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#012FA7',
  },
  replacementBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  replacementYes: {
    backgroundColor: '#E8F5E9',
  },
  replacementNo: {
    backgroundColor: '#FFEBEE',
  },
  replacementText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  chatInputContainer: {
    width: '100%',
    marginBottom: 15,
    backgroundColor: '#F8F9FC',
    padding: 12,
    borderRadius: 12,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputWrapper: {
    flex: 1,
    position: 'relative',
  },
  newCommentInput: {
    minHeight: 40,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: '#012FA7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingRight: 40,
    paddingVertical: 8,
    color: '#012FA7',
    fontSize: 14,
    backgroundColor: '#FFFFFF',
  },
  attachIcon: {
    position: 'absolute',
    right: 10,
    top: 10,
  },
  attachIconText: {
    fontSize: 20,
  },
  sendButton: {
    marginLeft: 8,
    backgroundColor: '#012FA7',
    borderRadius: 8,
    padding: 10,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    width: 20,
    height: 20,
    tintColor: '#FFFFFF',
  },
  selectedFilesContainer: {
    marginTop: 10,
  },
  selectedFilesLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#012FA7',
    marginBottom: 5,
  },
  fileItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderRadius: 6,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  fileName: {
    color: '#012FA7',
    fontSize: 13,
    flex: 1,
  },
  removeFileText: {
    color: '#FF0000',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  chatMessagesContainer: {
    width: '100%',
    maxHeight: 300,
  },
  messageCard: {
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  messageTeacher: {
    backgroundColor: '#E3F2FD',
    marginRight: 20,
  },
  messageStudent: {
    backgroundColor: '#E8F5E9',
    marginLeft: 20,
  },
  messageHeader: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  messageSender: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  teacherSender: {
    color: '#1976D2',
  },
  studentSender: {
    color: '#388E3C',
  },
  messageDate: {
    fontSize: 11,
    color: '#666',
  },
  messageText: {
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
  },
  messageFiles: {
    marginTop: 8,
    gap: 6,
  },
  messageFileChip: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    padding: 8,
    borderRadius: 6,
  },
  messageFileText: {
    color: '#1976D2',
    fontSize: 12,
  },
  emptyChat: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyChatIcon: {
    fontSize: 48,
    marginBottom: 10,
    opacity: 0.3,
  },
  emptyChatText: {
    fontSize: 16,
    color: '#666',
  },
});
